### ISSUE TITLE
Code migrated from cuda with dpct failed to compile with hip backend on AMD MI100 GPU

### ISSUE THREAD

**Issue by mazhaojia123** [oneapi-src/SYCLomatic#708] opened 2023-03-04 04:12 UTC
## Description

1. **Code migrated from cuda with dpct failed to compile with hip backend on AMD MI100 GPU**; 
2. The porting process below succeed on a nvidia rtx 3090 and got correct output. 
3. The problem: **How to port the cuda codes to sycl and run on AMD GPUs?**

## Environment
1. intel/llvm sycl branch; build with: 
    1. `python $DPCPP_HOME/llvm/buildbot/configure.py --hip`
    4. `python $DPCPP_HOME/llvm/buildbot/compile.py`
    5. `export PATH=$DPCPP_HOME/llvm/build/bin:$PATH
    export LD_LIBRARY_PATH=$DPCPP_HOME/llvm/build/lib:$LD_LIBRARY_PATH`
2. dpct from Intel® oneAPI Base Toolkit 2023; with setvars `source /path/to/oneapi/setvars.sh`
3. ubuntu20
6. amd MI100
7. ROCm-5.2.0

## Cuda codes
```cpp
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define FLOAT float
#define INT int
#define CEIL_DIV(m,n) ( (m) + (n) - 1 ) / (n)

#define A(i,j) A[(i) + (j)*lda]
#define B(i,j) B[(i) + (j)*ldb]
#define C(i,j) C[(i) + (j)*ldc]

void randomize_matrix(FLOAT* mat, int N);
void copy_matrix(FLOAT *src, FLOAT *dest, int n);
void test_mysgemm_v1(INT M, INT N, INT K, FLOAT alpha, FLOAT *A, FLOAT *B, FLOAT beta, FLOAT *C);

__global__  __launch_bounds__(1024)
void mysgemm_v1(int M, int N, int K, float alpha, float* A, float* B, float beta, float* C){
    int lda = M, ldb = K, ldc = M;
    int tx = threadIdx.x, ty = threadIdx.y;
    int bx = blockIdx.x, by = blockIdx.y;

    A = &A((bx<<5),0);
    B = &B(0,(by<<5));
    C = &C((bx<<5),(by<<5));
    float tmp=0.;
    for (int k_count = 0; k_count<K; k_count++){

        tmp += A(tx, k_count) * B(k_count, ty);
    }
    C(tx,ty) = alpha * tmp + beta*C(tx,ty);
}

int main() {

    int SIZE[24];
    for (int i=0;i<24;i++) SIZE[i]=(i+1)<<8;
	int upper_limit=8;


    FLOAT *A=NULL,*B=NULL,*C=NULL,*C_ref=NULL;//host matrices
    FLOAT *dA=NULL,*dB=NULL,*dC=NULL,*dC_ref=NULL;//device matrices
    // alpha 和 beta 两个系数，我们手动指定
    FLOAT alpha = 1.0, beta = 0.;//two arbitary input parameters
	

    float elapsed_time;
    cudaEvent_t beg, end;
    cudaEventCreate(&beg);
    cudaEventCreate(&end);


    int max_size;
    max_size = SIZE[upper_limit - 1];


    A=(FLOAT *)malloc(sizeof(FLOAT)*max_size*max_size);
    B=(FLOAT *)malloc(sizeof(FLOAT)*max_size*max_size);
    C=(FLOAT *)malloc(sizeof(FLOAT)*max_size*max_size);
    C_ref=(FLOAT *)malloc(sizeof(FLOAT)*max_size*max_size);
	

    randomize_matrix(A,max_size*max_size);randomize_matrix(B,max_size*max_size);
    randomize_matrix(C,max_size*max_size);copy_matrix(C,C_ref,max_size*max_size);


    cudaMalloc((void**) &dA, sizeof(FLOAT)*max_size*max_size);
    cudaMalloc((void**) &dB, sizeof(FLOAT)*max_size*max_size);
    cudaMalloc((void**) &dC, sizeof(FLOAT)*max_size*max_size);
    cudaMalloc((void**) &dC_ref, sizeof(FLOAT)*max_size*max_size);
    cudaMemcpy(dA, A, sizeof(FLOAT)*max_size*max_size, cudaMemcpyHostToDevice);
    cudaMemcpy(dB, B, sizeof(FLOAT)*max_size*max_size, cudaMemcpyHostToDevice);
    cudaMemcpy(dC, C, sizeof(FLOAT)*max_size*max_size, cudaMemcpyHostToDevice);
    cudaMemcpy(dC_ref, C_ref, sizeof(FLOAT)*max_size*max_size, cudaMemcpyHostToDevice);


	int m, n, k; // 输入矩阵的 size
	int n_count, N=10;
    for (int i_count=0;i_count<upper_limit;i_count++){

        m=n=k=SIZE[i_count];
        printf("\nM=N=K=%d:\n",m);

		test_mysgemm_v1(m, n, k, alpha, dA, dB, beta, dC);
		cudaDeviceSynchronize();

		cudaMemcpy(C, dC, sizeof(FLOAT)*m*n, cudaMemcpyDeviceToHost);
		cudaDeviceSynchronize();

		cudaEventRecord(beg);
		for (n_count=0;n_count<N;n_count++){
			test_mysgemm_v1(m, n, k, alpha, dA, dB, beta, dC);
		}

        cudaEventRecord(end);
        cudaEventSynchronize(beg);
        cudaEventSynchronize(end);
        cudaEventElapsedTime(&elapsed_time, beg, end);
        elapsed_time /= 1000.;

        printf("Average elapsed time: %f second, performance: %f GFLOPS.\n", elapsed_time/N,2.*1e-9*N*m*n*k/elapsed_time);
        fflush(stdout);
        copy_matrix(C_ref,C,m*n);//sync C with cuBLAS to prepare for the next run
    }
}

void randomize_matrix(FLOAT* mat, int N){
    srand(time(NULL)); int i;
    for (i = 0; i < N; i++) {
        FLOAT tmp = (float)(rand() % 5) + 0.01 * (rand() % 5);
        tmp = (rand() % 2 == 0) ? tmp : tmp * (-1.);
        //tmp = i;
        mat[i] = tmp;
    }
}

void copy_matrix(FLOAT *src, FLOAT *dest, int n){
    int i;
    for (i = 0; src + i && dest + i && i < n; i++) *(dest + i) = *(src + i);
    if (i != n) printf("copy failed at %d while there are %d elements in total.\n", i, n);
}

void test_mysgemm_v1(INT M, INT N, INT K, FLOAT alpha, FLOAT *A, FLOAT *B, FLOAT beta, FLOAT *C){
    cudaDeviceSynchronize();
    dim3 blockDim(32,32);
    dim3 gridDim(CEIL_DIV(M,32),CEIL_DIV(N,32));
    mysgemm_v1<<<gridDim, blockDim>>>(M,N,K,alpha,A,B,beta,C);
    cudaDeviceSynchronize();
}
```

## Migrate cuda codes with dpct

```sh
dpct --out-root tmp/dpcpp naive.cu --cuda-include-path=/home/mazhaojia/repos/cuda/include
```

## Output of dpct

```
root@gxn1275:/home/mazhaojia/dpct-study/tmp# dpct --out-root tmp/dpcpp naive.cu --cuda-include-path=/home/mazhaojia/repos/cuda/include
NOTE: Could not auto-detect compilation database for file 'naive.cu' in '/home/mazhaojia/dpct-study/tmp' or any parent directory.
Processing: /home/mazhaojia/dpct-study/tmp/naive.cu
/home/mazhaojia/dpct-study/tmp/naive.cu:134:5: warning: DPCT1049:0: The work-group size passed to the SYCL kernel may exceed the limit. To get the device limit, query info::device::max_work_group_size. Adjust the work-group size if needed.
    mysgemm_v1<<<gridDim, blockDim>>>(M,N,K,alpha,A,B,beta,C);
    ^
/home/mazhaojia/dpct-study/tmp/naive.cu:97:3: warning: DPCT1012:1: Detected kernel execution time measurement pattern and generated an initial code for time measurements in SYCL. You can change the way time is measured depending on your goals.
                cudaEventRecord(beg);
                ^
/home/mazhaojia/dpct-study/tmp/naive.cu:102:9: warning: DPCT1012:2: Detected kernel execution time measurement pattern and generated an initial code for time measurements in SYCL. You can change the way time is measured depending on your goals.
        cudaEventRecord(end);
        ^
Processed 1 file(s) in -in-root folder "/home/mazhaojia/dpct-study/tmp"

See Diagnostics Reference to resolve warnings and complete the migration:
https://software.intel.com/content/www/us/en/develop/documentation/intel-dpcpp-compatibility-tool-user-guide/top/diagnostics-reference.html
```

## Codes from dpct

```cpp
#include <sycl/sycl.hpp>
#include <dpct/dpct.hpp>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <chrono>

#define FLOAT float
#define INT int
#define CEIL_DIV(m,n) ( (m) + (n) - 1 ) / (n)

#define A(i,j) A[(i) + (j)*lda]
#define B(i,j) B[(i) + (j)*ldb]
#define C(i,j) C[(i) + (j)*ldc]

void randomize_matrix(FLOAT* mat, int N);
void copy_matrix(FLOAT *src, FLOAT *dest, int n);
void test_mysgemm_v1(INT M, INT N, INT K, FLOAT alpha, FLOAT *A, FLOAT *B, FLOAT beta, FLOAT *C);


void mysgemm_v1(int M, int N, int K, float alpha, float* A, float* B, float beta, float* C,
                sycl::nd_item<3> item_ct1){
    int lda = M, ldb = K, ldc = M;
    int tx = item_ct1.get_local_id(2), ty = item_ct1.get_local_id(1);
    int bx = item_ct1.get_group(2), by = item_ct1.get_group(1);


    A = &A((bx<<5),0);
    B = &B(0,(by<<5));
    C = &C((bx<<5),(by<<5));
    float tmp=0.;
    for (int k_count = 0; k_count<K; k_count++){

        tmp += A(tx, k_count) * B(k_count, ty);
    }
    C(tx,ty) = alpha * tmp + beta*C(tx,ty);
}

int main() {
    dpct::device_ext &dev_ct1 = dpct::get_current_device();
    sycl::queue &q_ct1 = dev_ct1.default_queue();

    int SIZE[24];
    for (int i=0;i<24;i++) SIZE[i]=(i+1)<<8;
	int upper_limit=8;


    FLOAT *A=NULL,*B=NULL,*C=NULL,*C_ref=NULL;//host matrices
    FLOAT *dA=NULL,*dB=NULL,*dC=NULL,*dC_ref=NULL;//device matrices

    FLOAT alpha = 1.0, beta = 0.;//two arbitary input parameters
	
    float elapsed_time;
    dpct::event_ptr beg, end;
    std::chrono::time_point<std::chrono::steady_clock> beg_ct1;
    std::chrono::time_point<std::chrono::steady_clock> end_ct1;
    beg = new sycl::event();
    end = new sycl::event();

        int max_size;
	max_size = SIZE[upper_limit - 1];


    A=(FLOAT *)malloc(sizeof(FLOAT)*max_size*max_size);
    B=(FLOAT *)malloc(sizeof(FLOAT)*max_size*max_size);
    C=(FLOAT *)malloc(sizeof(FLOAT)*max_size*max_size);
    C_ref=(FLOAT *)malloc(sizeof(FLOAT)*max_size*max_size);
	

    randomize_matrix(A,max_size*max_size);randomize_matrix(B,max_size*max_size);
    randomize_matrix(C,max_size*max_size);copy_matrix(C,C_ref,max_size*max_size);


    dA = (float *)sycl::malloc_device(sizeof(FLOAT) * max_size * max_size,
                                      q_ct1);
    dB = (float *)sycl::malloc_device(sizeof(FLOAT) * max_size * max_size,
                                      q_ct1);
    dC = (float *)sycl::malloc_device(sizeof(FLOAT) * max_size * max_size,
                                      q_ct1);
    dC_ref = (float *)sycl::malloc_device(sizeof(FLOAT) * max_size * max_size,
                                          q_ct1);
    q_ct1.memcpy(dA, A, sizeof(FLOAT) * max_size * max_size);
    q_ct1.memcpy(dB, B, sizeof(FLOAT) * max_size * max_size);
    q_ct1.memcpy(dC, C, sizeof(FLOAT) * max_size * max_size);
    q_ct1.memcpy(dC_ref, C_ref, sizeof(FLOAT) * max_size * max_size).wait();


	int m, n, k; 
	int n_count, N=10;
    for (int i_count=0;i_count<upper_limit;i_count++){

        m=n=k=SIZE[i_count];
        printf("\nM=N=K=%d:\n",m);


		test_mysgemm_v1(m, n, k, alpha, dA, dB, beta, dC);
                dev_ct1.queues_wait_and_throw();


                q_ct1.memcpy(C, dC, sizeof(FLOAT) * m * n).wait();
                dev_ct1.queues_wait_and_throw();


                /*
                DPCT1012:1: Detected kernel execution time measurement pattern
                and generated an initial code for time measurements in SYCL. You
                can change the way time is measured depending on your goals.
                */
                beg_ct1 = std::chrono::steady_clock::now();
                for (n_count=0;n_count<N;n_count++){
			test_mysgemm_v1(m, n, k, alpha, dA, dB, beta, dC);
		}

        /*
        DPCT1012:2: Detected kernel execution time measurement pattern and
        generated an initial code for time measurements in SYCL. You can change
        the way time is measured depending on your goals.
        */
        end_ct1 = std::chrono::steady_clock::now();
        elapsed_time =
            std::chrono::duration<float, std::milli>(end_ct1 - beg_ct1).count();
        elapsed_time /= 1000.;

        printf("Average elapsed time: %f second, performance: %f GFLOPS.\n", elapsed_time/N,2.*1e-9*N*m*n*k/elapsed_time);
        fflush(stdout);
        copy_matrix(C_ref,C,m*n);//sync C with cuBLAS to prepare for the next run
    }
}

void randomize_matrix(FLOAT* mat, int N){
    srand(time(NULL)); int i;
    for (i = 0; i < N; i++) {
        FLOAT tmp = (float)(rand() % 5) + 0.01 * (rand() % 5);
        tmp = (rand() % 2 == 0) ? tmp : tmp * (-1.);
        //tmp = i;
        mat[i] = tmp;
    }
}

void copy_matrix(FLOAT *src, FLOAT *dest, int n){
    int i;
    for (i = 0; src + i && dest + i && i < n; i++) *(dest + i) = *(src + i);
    if (i != n) printf("copy failed at %d while there are %d elements in total.\n", i, n);
}

void test_mysgemm_v1(INT M, INT N, INT K, FLOAT alpha, FLOAT *A, FLOAT *B,
                     FLOAT beta, FLOAT *C) {
    dpct::device_ext &dev_ct1 = dpct::get_current_device();
    dev_ct1.queues_wait_and_throw();
    sycl::range<3> blockDim(1, 32, 32);
    sycl::range<3> gridDim(1, CEIL_DIV(N, 32), CEIL_DIV(M, 32));
    /*
    DPCT1049:0: The work-group size passed to the SYCL kernel may exceed the
    limit. To get the device limit, query info::device::max_work_group_size.
    Adjust the work-group size if needed.
    */
    dpct::get_default_queue().parallel_for(
        sycl::nd_range<3>(gridDim * blockDim, blockDim),
        [=](sycl::nd_item<3> item_ct1) {
            mysgemm_v1(M, N, K, alpha, A, B, beta, C, item_ct1);
        });
    dev_ct1.queues_wait_and_throw();
}
```

## Compile *.dp.cpp with clang++

```sh
clang++ -fsycl -fsycl-targets=amdgcn-amd-amdhsa \
        -Xsycl-target-backend --offload-arch=gfx908 \
        -o naive_dpcpp_hip naive.dp.cpp ;
```

## Failed to compile

```
In file included from naive.dp.cpp:2:
In file included from /home/mazhaojia/intel/oneapi/dpcpp-ct/2023.0.0/include/dpct/dpct.hpp:21:
In file included from /home/mazhaojia/intel/oneapi/dpcpp-ct/2023.0.0/include/dpct/image.hpp:14:
/home/mazhaojia/intel/oneapi/dpcpp-ct/2023.0.0/include/dpct/memory.hpp:767:26: warning: 'get_access' is deprecated: get_access for host_accessor is deprecated, please use get_host_access instead [-Wdeprecated-declarations]
      BufferOffset.first.get_access<sycl::access_mode::read_write>()
                         ^
/home/mazhaojia/pkgs/llvm/build/bin/../include/sycl/buffer.hpp:513:37: note: 'get_access' has been explicitly marked deprecated here
          accessor_property_list<>> get_access(const detail::code_location
                                    ^
In file included from naive.dp.cpp:2:
In file included from /home/mazhaojia/intel/oneapi/dpcpp-ct/2023.0.0/include/dpct/dpct.hpp:21:
In file included from /home/mazhaojia/intel/oneapi/dpcpp-ct/2023.0.0/include/dpct/image.hpp:14:
/home/mazhaojia/intel/oneapi/dpcpp-ct/2023.0.0/include/dpct/memory.hpp:767:26: warning: 'get_access<sycl::access::mode::read_write>' is deprecated: get_access for host_accessor is deprecated, please use get_host_access instead [-Wdeprecated-declarations]
      BufferOffset.first.get_access<sycl::access_mode::read_write>()
                         ^
/home/mazhaojia/pkgs/llvm/build/bin/../include/sycl/buffer.hpp:507:3: note: 'get_access<sycl::access::mode::read_write>' has been explicitly marked deprecated here
  __SYCL2020_DEPRECATED("get_access for host_accessor is deprecated, please "
  ^
/home/mazhaojia/pkgs/llvm/build/bin/../include/sycl/detail/defines_elementary.hpp:48:40: note: expanded from macro '__SYCL2020_DEPRECATED'
#define __SYCL2020_DEPRECATED(message) __SYCL_DEPRECATED(message)
                                       ^
/home/mazhaojia/pkgs/llvm/build/bin/../include/sycl/detail/defines_elementary.hpp:39:38: note: expanded from macro '__SYCL_DEPRECATED'
#define __SYCL_DEPRECATED(message) [[deprecated(message)]]
                                     ^
In file included from naive.dp.cpp:1:
In file included from /home/mazhaojia/pkgs/llvm/build/bin/../include/sycl/sycl.hpp:15:
/home/mazhaojia/pkgs/llvm/build/bin/../include/sycl/atomic_ref.hpp:132:3: error: static assertion failed due to requirement '(sycl::memory_order)5 != sycl::memory_order::seq_cst': seq_cst memory order is not supported on AMDGPU
  static_assert(DefaultOrder != sycl::memory_order::seq_cst,
  ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mazhaojia/pkgs/llvm/build/bin/../include/sycl/atomic_ref.hpp:279:14: note: in instantiation of template class 'sycl::detail::atomic_ref_base<unsigned int, sycl::memory_order::seq_cst, sycl::memory_scope::device, sycl::access::address_space::global_space>' requested here
    : public atomic_ref_base<T, DefaultOrder, DefaultScope, AddressSpace> {
             ^
/home/mazhaojia/pkgs/llvm/build/bin/../include/sycl/atomic_ref.hpp:715:14: note: in instantiation of template class 'sycl::detail::atomic_ref_impl<unsigned int, false, sycl::memory_order::seq_cst, sycl::memory_scope::device, sycl::access::address_space::global_space>' requested here
    : public detail::atomic_ref_impl<T, sizeof(T) == 8, DefaultOrder,
             ^
/home/mazhaojia/intel/oneapi/dpcpp-ct/2023.0.0/include/dpct/util.hpp:434:25: note: in instantiation of template class 'sycl::atomic_ref<unsigned int, sycl::memory_order::seq_cst, sycl::memory_scope::device, sycl::access::address_space::global_space>' requested here
    old_arrive = counter.fetch_add(inc);
                        ^
/home/mazhaojia/pkgs/llvm/build/bin/../include/sycl/atomic_ref.hpp:132:30: note: expression evaluates to '5 != 5'
  static_assert(DefaultOrder != sycl::memory_order::seq_cst,
                ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from naive.dp.cpp:2:
In file included from /home/mazhaojia/intel/oneapi/dpcpp-ct/2023.0.0/include/dpct/dpct.hpp:21:
In file included from /home/mazhaojia/intel/oneapi/dpcpp-ct/2023.0.0/include/dpct/image.hpp:15:
/home/mazhaojia/intel/oneapi/dpcpp-ct/2023.0.0/include/dpct/util.hpp:436:35: error: no member named 'load' in 'sycl::atomic_ref<unsigned int, sycl::memory_order::seq_cst, sycl::memory_scope::device, sycl::access::address_space::global_space>'
    while (((old_arrive ^ counter.load()) & 0x80000000) == 0)
                          ~~~~~~~ ^
/home/mazhaojia/intel/oneapi/dpcpp-ct/2023.0.0/include/dpct/util.hpp:469:26: error: no member named 'fetch_add' in 'sycl::atomic_ref<unsigned int, sycl::memory_order::seq_cst, sycl::memory_scope::device, sycl::access::address_space::global_space>'
    old_arrive = counter.fetch_add(inc);
                 ~~~~~~~ ^
/home/mazhaojia/intel/oneapi/dpcpp-ct/2023.0.0/include/dpct/util.hpp:471:35: error: no member named 'load' in 'sycl::atomic_ref<unsigned int, sycl::memory_order::seq_cst, sycl::memory_scope::device, sycl::access::address_space::global_space>'
    while (((old_arrive ^ counter.load()) & 0x80000000) == 0)
                          ~~~~~~~ ^
2 warnings and 4 errors generated.
```

**Comment by tomflinda** [comment] 2023-03-07 03:18
@mazhaojia123 thanks for trying SYCLomatic,

1.  Root cause for the compile error:
```
/home/mazhaojia/pkgs/llvm/build/bin/../include/sycl/atomic_ref.hpp:132:3: error: static assertion failed due to requirement '(sycl::memory_order)5 != sycl::memory_order::seq_cst': seq_cst memory order is not supported on AMDGPU
  static_assert(DefaultOrder != sycl::memory_order::seq_cst,
```
is that seq_cst memory order is not supported on AMDGPU, which is shown in warning msg, more detail pls refer to https://github.com/intel/llvm/blob/d2bc9d10a50acc317e727b9b6c06a44646ed9a18/sycl/include/sycl/atomic_ref.hpp#LL133C17-L133C64
You can file a feature issue for seq_cst memory order implementation on AMDGPU device in https://github.com/intel/llvm/issues.

2. WA for this issue to comment function nd_range_barrier() in  file `dpcpp-ct/2023.0.0/include/dpct/util.hpp(Line 403--Line476)`, shown as below:

```
/// Synchronize work items from all work groups within a SYCL kernel.
/// \param [in] item:  Represents a work group.
/// \param [in] counter: An atomic object defined on a device memory which can
/// be accessed by work items in all work groups. The initial value of the
/// counter should be zero.
/// Note: Please make sure that all the work items of all work groups within
/// a SYCL kernel can be scheduled actively at the same time on a device.
template <int dimensions = 3>
inline void
nd_range_barrier(sycl::nd_item<dimensions> item,
                 sycl::atomic_ref<
                     unsigned int, sycl::memory_order::seq_cst,
                     sycl::memory_scope::device,
                     sycl::access::address_space::global_space> &counter) {

  static_assert(dimensions == 3, "dimensions must be 3.");

  unsigned int num_groups = item.get_group_range(2) * item.get_group_range(1) *
                            item.get_group_range(0);

  item.barrier();

  if (item.get_local_linear_id() == 0) {
    unsigned int inc = 1;
    unsigned int old_arrive = 0;
    bool is_group0 =
        (item.get_group(2) + item.get_group(1) + item.get_group(0) == 0);
    if (is_group0) {
      inc = 0x80000000 - (num_groups - 1);
    }

    old_arrive = counter.fetch_add(inc);
    // Synchronize all the work groups
    while (((old_arrive ^ counter.load()) & 0x80000000) == 0)
      ;
  }

  item.barrier();
}

/// Synchronize work items from all work groups within a SYCL kernel.
/// \param [in] item:  Represents a work group.
/// \param [in] counter: An atomic object defined on a device memory which can
/// be accessed by work items in all work groups. The initial value of the
/// counter should be zero.
/// Note: Please make sure that all the work items of all work groups within
/// a SYCL kernel can be scheduled actively at the same time on a device.
template <>
inline void
nd_range_barrier(sycl::nd_item<1> item,
                 sycl::atomic_ref<
                     unsigned int, sycl::memory_order::seq_cst,
                     sycl::memory_scope::device,
                     sycl::access::address_space::global_space> &counter) {
  unsigned int num_groups = item.get_group_range(0);

  item.barrier();

  if (item.get_local_linear_id() == 0) {
    unsigned int inc = 1;
    unsigned int old_arrive = 0;
    bool is_group0 = (item.get_group(0) == 0);
    if (is_group0) {
      inc = 0x80000000 - (num_groups - 1);
    }

    old_arrive = counter.fetch_add(inc);
    // Synchronize all the work groups
    while (((old_arrive ^ counter.load()) & 0x80000000) == 0)
      ;
  }

  item.barrier();
}
```

**Comment by zjin-lcf** [comment] 2023-03-08 00:15
Are there any reference/document for explaining the logics of synchronizing all work-groups ?

**Comment by zjin-lcf** [comment] 2023-03-08 00:20
"You can file a feature issue for seq_cst memory order implementation on AMDGPU device in https://github.com/intel/llvm/issues."

Could you please clarify the issue ? Should this issue be directed to AMD developers ?

**Comment by tomflinda** [comment] 2023-03-08 07:46
@zjin-lcf  
1. the root cause for this issue is that  seq_cst memory order is not implemented on AMDGPU device in intel SYCL compiler, you can file a feature request to intel SYCL compiler community，and I will also report this issue to compiler team.
2. nd_range_barrier is used to migrate cross group synchronization in cuda side, here is the demo case   https://github.com/oneapi-src/SYCLomatic/blob/f803ba8c8ba6929ad97583bc4076498359e5d324/clang/test/dpct/sync_api.cu#L100
About document for helper functions, we are WIP to public it.

**Comment by mazhaojia123** [comment] 2023-03-10 08:00
@tomflinda Thanks. The solution works for me.

**Comment by zjin-lcf** [comment] 2023-03-10 19:08
Thanks.

**Comment by zjin-lcf** [comment] 2023-12-20 02:26
@tomflinda   Do you hear from the compiler team about the issue?  Quite a few people encountered the issues.  Thanks.

**Comment by tomflinda** [comment] 2024-06-05 01:29
@zjin-lcf  No,  no further action needed in SYCLomatic side, so I close this issue.

**Closed as completed by tomflinda** 2024-06-05 01:29 UTC
