### ISSUE TITLE
visual studio 2019安装了intel的扩展后，并没有migrate projects to DPC++的选项

### ISSUE THREAD

**Issue by CHzhangi** [oneapi-src/SYCLomatic#1436] opened 2023-11-18 15:59 UTC
![图片](https://github.com/oneapi-src/SYCLomatic/assets/80149371/8519fd3d-ba44-4a2e-a7cf-d0d16821aebf)

**Comment by CHzhangi** [comment] 2023-11-18 16:02
![图片](https://github.com/oneapi-src/SYCLomatic/assets/80149371/ca54f58d-c95d-4b90-831e-2038afbc3229)

**Comment by tomflinda** [comment] 2023-11-20 00:21
@CHzhangi  thanks for your report, we will try to reproduce it and locate the root cause ASAP.

**Comment by ddup-zg** [comment] 2023-11-20 01:07
@CHzhangi This is not a bug. 
No "Migrate Project to DPC++" submenu in your environment is expected, because you only installed Compilers component, and did not install Intel® DPC++ Compatibility Tool component.
You should download and install Intel® DPC++ Compatibility Tool component to use "Migrate Project to DPC++" submenu. Or you could directly install Intel oneAPI Base Toolkit which contains both Compilers and Intel® DPC++ Compatibility Tool components.

**Comment by CHzhangi** [comment] 2023-11-20 01:10
Oh thank you i will try it



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ddup-zg ***@***.***&gt;
发送时间: 2023年11月20日 09:07
收件人: oneapi-src/SYCLomatic ***@***.***&gt;
抄送: ZhangCH ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [oneapi-src/SYCLomatic] visual studio 2019安装了intel的扩展后，并没有migrate projects to DPC++的选项 (Issue #1436)





 
@CHzhangi This is not a bug.
 No "Migrate Project to DPC++" submenu in your environment is expected, because you only installed Compilers component, and did not install Intel® DPC++ Compatibility Tool component.
 You should download and install Intel® DPC++ Compatibility Tool component to use "Migrate Project to DPC++" submenu. Or you could directly install Intel oneAPI Base Toolkit which contains both Compilers and Intel® DPC++ Compatibility Tool components.

**Comment by tomflinda** [comment] 2023-11-21 00:08
@CHzhangi pls close this issue, if verification is passed, thanks.

**Closed as completed** 2023-11-21 02:33 UTC
Labels: bug
