### ISSUE TITLE
 deviceProp.maxThreadsPerMultiProcessor != deviceProp.get_max_work_items_per_compute_unit() ?

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#496] opened 2023-01-12 19:19 UTC
deviceProp.maxThreadsPerMultiProcessor  is 2048 and deviceProp.get_max_work_items_per_compute_unit() is 1024 on an NVIDIA GPU.

```
  dpct version 16.0.0. Codebase:(536eeb8014b1570a8b65aee511cbe2ba664e3962)
  cudaDeviceProp deviceProp;
  cudaGetDeviceProperties(&deviceProp, 0);
  const int mTpSM = deviceProp.maxThreadsPerMultiProcessor;
```

**Comment by tomflinda** [comment] 2023-01-16 08:25
@zjin-lcf we plan to sync with compiler team what the root cause is.

**Comment by zjin-lcf** [comment] 2023-01-16 11:57
okay

**Comment by tomflinda** [comment] 2024-06-05 01:25
@zjin-lcf We have reported this issue to the compiler team and https://github.com/intel/llvm/issues/7997 also track its status, so there is no further action needed in SYCLomatic, I close this issue.

**Closed as completed by tomflinda** 2024-06-05 01:25 UTC
Labels: bug
