### ISSUE TITLE
The bh program hangs

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#791] opened 2023-03-31 18:44 UTC
Running the SYCL program, after migrating the Cuda example (https://github.com/zjin-lcf/HeCBench/tree/master/bh-cuda) with SYCLomatic, hangs on an NVIDIA V100 GPU. Thank you for your investigation. 

Output of running the Cuda example:
 
./main 100000 100
ECL-BH v4.5
Copyright (c) 2010-2020 Texas State University
configuration: 100000 bodies, 100 time steps
Total kernel execution time: 4.7116 s

Reference
https://github.com/intel/llvm/discussions/5516

**Comment by tomflinda** [comment] 2023-04-06 06:31
@zjin-lcf have you tried it on cpu device with small configuration, like "./main 10 10"?
on my machine, on cpu device "./main 10 10" run passed.

**Comment by zjin-lcf** [comment] 2023-04-06 11:35
The program passes on a GPU for small configuration. Thanks.

**Comment by tomflinda** [comment] 2023-04-07 02:06
@zjin-lcf I have reported this issue to SYCL compiler team to locate the root cause and wait for their feedback.

**Comment by zjin-lcf** [comment] 2023-04-10 21:37
Thank you for reporting the issue for me. I find that another SYCL program also hangs after migrating the Cuda program. 
https://github.com/zjin-lcf/HeCBench/tree/master/columnarSolver-cuda

**Comment by tomflinda** [comment] 2024-06-05 01:27
@zjin-lcf  these it no further action needed in SYCLomatic side, so I close this issue.

**Closed as completed by tomflinda** 2024-06-05 01:27 UTC
Labels: bug
