### ISSUE TITLE
Please preserve filename case sensitivity

### ISSUE THREAD

**Issue by sunzhuoshi** [oneapi-src/SYCLomatic#903] opened 2023-05-11 00:49 UTC
**Is your feature request related to a problem? Please describe**
Version: 2023.1.0
OS: Windows 11
Source file name like: "FirstSecond.u" will be translated to "firstsecond.dp.cpp"

**Describe the solution you would like**
Please preserve filename case sensitivity, translate "FirstSecond.u" to "FirstSecond.dp.cpp", instead of "firstsecond.dp.cpp"

**Describe alternatives you have considered**
None

**Additional context**
None

**Comment by tomflinda** [comment] 2023-05-11 05:38
@sunzhuoshi thanks to report this issue, 
Windows file system treats file and directory names as case-insensitive when it comes to accessing or referencing them,
However, for SYCLomatic, it should preserve the case of the migrated file name same as original one except for extension name.
we will plan to implement it.

**Comment by fq1820** [comment] 2023-05-16 13:31
I have located the root cause and here is my pr : https://github.com/oneapi-src/SYCLomatic/pull/909

**Comment by tomflinda** [comment] 2023-05-17 03:06
@fq1820 thanks for submitting the PR, we will review it after it passes alloy test.

**Comment by tomflinda** [comment] 2023-05-22 02:50
@fq1820 your PR https://github.com/oneapi-src/SYCLomatic/pull/909 has been merged, so I have closed this issue.
Also, welcome for new PRs for other issues that you are interested in and plan to fix them.

**Closed as completed by tomflinda** 2023-05-22 02:50 UTC
Labels: enhancement
