### ISSUE TITLE
no type named 'buffer_allocator' in namespace 'sycl'

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#654] opened 2023-02-23 01:21 UTC
Compiling a program produces the error:  include/dpct/dpl_extras/memory.h:36:11: error: no type named 'buffer_allocator' in namespace 'sycl'; did you mean 'image_allocator'?

```
#include <sycl/sycl.hpp>
#include <dpct/dpct.hpp>
#include <dpct/dpl_utils.hpp>

int main() {
}
```

I think the issue might be solved by:

```
using __buffer_allocator =
//#if __LIBSYCL_VERSION >= 50707
    sycl::buffer_allocator<typename make_allocatable<_DataT>::type>;
//#else
    //sycl::buffer_allocator;
//#endif
```

**Comment by tomflinda** [comment] 2023-02-23 06:20
@zjin-lcf  this is caused by action that  dpl rename macro PR https://github.com/oneapi-src/oneDPL/pull/696, which is merged in Nov 25, and PR for SYCLomatic to match the new macro name is https://github.com/oneapi-src/SYCLomatic/pull/465, which has been merged  on Jan 16 2023.

So WA is to update the dpl version after Nov 25, and use SYCLomatic daily build after Jan 16.  Also, if your app does not use __buffer_allocator , comment it like what you did is OK.

**Closed as completed** 2023-02-23 12:33 UTC
Labels: bug

**Comment by tomflinda** [comment] 2023-03-28 08:22
#465
